name: "Build and Tests"

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m venv .venv && export PATH=".venv/bin:$PATH"
          python -m pip install uv
          python -m uv pip install --upgrade pip wheel setuptools
          python -m uv pip install -e ."[all]"

      - name: Run pre-commit tests
        uses: pre-commit/action@v3.0.1

      - name: Test with PyTest
        run: |
          python -m venv .venv && export PATH=".venv/bin:$PATH"
          pytest -v